# This is a GitHub Actions workflow file for automating the daily pumpkin harvest process.
name: Daily Pumpkin Harvest

on:
  schedule:
    - cron: "45 21 * * *" # This is 23:45 Paris time (UTC+2) during summer time

jobs:
  run-harvest-script:
    runs-on: ubuntu-latest
    env:
      WORKER: ${{ secrets.WORKER }}
      TOKEN: ${{ secrets.API_TOKEN }}
      BARN: ${{ secrets.BARN_API_URL }}
      PUMPKIN_FIELD: ${{ secrets.PUMPKIN_FIELD }}
      TRACTOR: ${{ secrets.TRACTOR }}
      TRAILER: ${{ secrets.TRAILER }}
      PITCHFORK: ${{ secrets.PITCHFORK }}
      HARVEST_SPOT: ${{ secrets.HARVEST_SPOT }}
      HARVEST_ACTION: ${{ secrets.HARVEST_ACTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install requests from requirements.txt

      - name: Run harvest script
        run: python harvest_pumpkins.py
        working-directory: ./pumpkin_harvest
